inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
